# Generated by Django 5.2.8 on 2025-11-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FaultPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Va", models.FloatField()),
                ("Vb", models.FloatField()),
                ("Vc", models.FloatField()),
                ("Ia", models.FloatField()),
                ("Ib", models.FloatField()),
                ("Ic", models.FloatField()),
                ("G", models.IntegerField()),
                ("A", models.IntegerField()),
                ("B", models.IntegerField()),
                ("C", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
